### ISSUE TITLE
how to fix build action for publish to Marketplace

### ISSUE THREAD

**Issue by neozhu** [madskristensen/DocumentHealth#2]
Error: The process 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VSSDK\VisualStudioIntegration\Tools\Bin\VsixPublisher.exe' failed with exit code 3762504530

**Comment by madskristensen** [comment]
This is a known bug that the VS extensibility team has fixed in 17.9 I believe. Publishing actually works even with that error being shown. As soon as GitHub updates to 17.9, the error will go away
